### ISSUE TITLE
El Dockerfile usado no sigue buenas prácticas

### ISSUE THREAD

**Issue by mcarmona99** [mcarmona99/CineTickets#46]
Se debe corregir el Dockerfile que representa el contenedor de los tests de la aplicación y mejorarlo en la medida de lo posible.

Debemos tener un Dockerfile correcto, siguiendo buenas prácticas, y adaptado de forma correcta a las clases o módulos que se están testeando, incluyendo optimización del tamaño del mismo durante su construcción o a continuación.

Referente al producto mínimamente viable Interno 3 (https://github.com/mcarmona99/CineTickets/milestone/7). En este hito en el que ampliamos el producto, se desarrolla la infraestructura necesaria para desplegar la aplicación en un contenedor. Es por esto que optimizar el Dockerfile es parte clave del PMV.

Issue no relacionada con ninguna historia de usuario ya que no se avanza con las mismas en este hito, que es puramente de infraestructura.

**Comment by mcarmona99** [comment]
Aplico cambios a la primera iteración del `Dockerfile`. Como referencia utilizo la documentación de `docker` para buenas practicas en `Dockerfile`: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

En primer lugar, elimino `COPY . /app` del Dockerfile, ya que se usarán volúmenes (`-v` flag) para hacer el mapeo del directorio.

A raíz de este cambio, y teniendo en cuenta que los tests se deben de lanzar con:

docker run -t -v `pwd`:/app/test nick-estudiante/nombre-del-repo

se cambiará el `WORKDIR` por `WORKDIR /app/test`, ya que `test` sera el directorio donde se encuentre el proyecto.

En segundo lugar, debemos de minimizar el número de capas. Esto sólo ocurre en versiones antiguas de Docker. Los comandos que crean capas son `RUN`, `COPY` y `ADD`, entre otros. Otras instrucciones crean imágenes temporales intermedias que no incrementan el tamaño de la construcción.

Para ello, mantengo la línea `RUN apk add gcc libc-dev libffi-dev` tal y como la tengo, en lugar de separar en varios `RUN apk add x`.

Otra buena práctica, que en este caso es puramente de estilo, es ordenar los argumentos de comandos en más de una línea.
Para cumplir este check, cambio `RUN apk add gcc libc-dev libffi-dev` por

```
RUN apk add \
  gcc \
  libc-dev \
  libffi-dev
```

Finalmente, creo un usuario no root que será el que ejecute la aplicación. Este usuario ejecutará también las sentencias pip install dentro del Dockerfile. Para cambiar a este usuario, uso `USER <usuario>`. Ejecutar pip con un usuario root es una mala práctica ya que podríamos tener problemas de seguridad al descargar e instalar paquetes externos (de PyPI). Ref: https://qastack.mx/ubuntu/802544/is-sudo-pip-install-still-a-broken-practice

Al crear un nuevo usuario, pypyr y poetry se instalan en el home del usuario: /home/cinetickets/.local/bin. También pasa con otras dependencias: 

```
  WARNING: The script normalizer is installed in '/home/cinetickets/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script doesitcache is installed in '/home/cinetickets/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script virtualenv is installed in '/home/cinetickets/.local/bin' which is not on PATH.
  ...
```

Usaremos ENV para actualizar la variable de entorno PATH que usa el software o paquetes instalados. Por ejemplo, como vemos en la docu, `ENV PATH=/usr/local/nginx/bin:$PATH` se asegura que `CMD ["nginx"]` funciona.
Para nuestro caso, usaremos
`ENV PATH=/home/cinetickets/.local/bin:$PATH
`

Buenas prácticas en instrucciones de Dockerfile:

`FROM`: es recomendable usar Alpine. ✅ 
`RUN`: como hemos mencionado anteriormente, ordenar los argumentos de sentencias complejas de RUN en más de una línea. ✅ 
`CMD`: es recomendable usar los comandos separados por palabra (tipo string) en una lista. Ex: `CMD ["executable", "param1", "param2"…]`. ✅ 
`USER`: si un servicio puede ser ejecutado sin privilegios, `USER` cambia a un usuario no root. Se deberá crear el usuario y grupo en el Dockerfile. ✅ 



**Tras todos estos cambios, tanto de buenas prácticas como necesarios (como por ejemplo el usuario), nuestra imagen tiene un tamaño de 224MB y queda de la siguiente forma:**

```Dockerfile
# Dockerfile para despliegue automático de la aplicación CineTickets. Ejecución de tests
FROM python:3.8-alpine3.13

# Instalación de deps del gestor de tareas y deps; y creación del usuario
RUN apk add \
    gcc \
    libc-dev \
    libffi-dev  \
    && addgroup -S cinetickets  \
    && adduser -S cinetickets -G cinetickets  # usuario y grupo, respectivamente

# Cambiar al usuario no root
USER cinetickets

# Cambio PATH para instalaciones en home de usuario no root
ENV PATH=/home/cinetickets/.local/bin:$PATH

# Instalación del gestor de dependencias y tareas
RUN pip install poetry pypyr

# Cambiamos de directorio a /app/test
WORKDIR /app/test

# Ejecutamos los tests con el task runner
CMD ["pypyr", "tests"]
```

Para construir la imagen:

```bash
$ docker build . -t mcarmona99/cinetickets
```

Para lanzar los tests (tengo que usar comillas ya que `pwd` tiene un path con espacios):

```
$ docker run -t -v "`pwd`:/app/test" mcarmona99/cinetickets

============================= test session starts ==============================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /app/test
collected 10 items                                                             

tests/test_Pelicula.py .....                                             [ 50%]
tests/test_Sala.py .                                                     [ 60%]
tests/test_exception.py ....                                             [100%]

=============================== warnings summary ===============================
../../home/cinetickets/.cache/pypoetry/virtualenvs/cinetickets-rAFghFJC-py3.8/lib/python3.8/site-packages/_pytest/cacheprovider.py:428
  /home/cinetickets/.cache/pypoetry/virtualenvs/cinetickets-rAFghFJC-py3.8/lib/python3.8/site-packages/_pytest/cacheprovider.py:428: PytestCacheWarning: cache could not write path /app/test/.pytest_cache/v/cache/nodeids
    config.cache.set("cache/nodeids", sorted(self.cached_nodeids))

../../home/cinetickets/.cache/pypoetry/virtualenvs/cinetickets-rAFghFJC-py3.8/lib/python3.8/site-packages/_pytest/stepwise.py:49
  /home/cinetickets/.cache/pypoetry/virtualenvs/cinetickets-rAFghFJC-py3.8/lib/python3.8/site-packages/_pytest/stepwise.py:49: PytestCacheWarning: cache could not write path /app/test/.pytest_cache/v/cache/stepwise
    session.config.cache.set(STEPWISE_CACHE_DIR, [])

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 10 passed, 2 warnings in 0.03s ========================
```

**Comment by JJ** [comment]
> Aplico cambios a la primera iteración del `Dockerfile`. Como referencia utilizo la documentación de `docker` para buenas practicas en `Dockerfile`: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
> 
> En primer lugar, elimino `COPY . /app` del Dockerfile, ya que se usarán volúmenes (`-v` flag) para hacer el mapeo del directorio.
> 
> A raíz de este cambio, y teniendo en cuenta que los tests se deben de lanzar con:
> 
> docker run -t -v `pwd`:/app/test nick-estudiante/nombre-del-repo
> 
> se cambiará el `WORKDIR` por `WORKDIR /app/test`, ya que `test` sera el directorio donde se encuentre el proyecto.
> 
> En segundo lugar, debemos de minimizar el número de capas. Esto sólo ocurre en versiones antiguas de Docker. Los comandos que crean capas son `RUN`, `COPY` y `ADD`, entre otros. Otras instrucciones crean imágenes temporales intermedias que no incrementan el tamaño de la construcción.
> 
> Para ello, mantengo la línea `RUN apk add gcc libc-dev libffi-dev` tal y como la tengo, en lugar de separar en varios `RUN apk add x`.
> 

Estás instalando esto para poder usar pip, cuando puedes descargarte el `wheel` de poetry ya compilado con wget (en vez de con curl) que ya está incorporado en Alpine. Eso ocurre porque en vez de entender lo que estáis haciendo, lo tratáis de llevar a cabo al pie de la letra.
